# Workspace packages configuration
packages:
  - "packages/*"
  - "apps/*"
  - "tools/*"
  - "."

# Catalogs - Centralizovano upravljanje verzijama kroz named catalogs
catalogs:
  # Core React Ecosystem - Stabilne verzije
  core:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1

  # TypeScript Ecosystem - Updated to specification requirements
  typescript:
    typescript: ^5.4.5
    "@types/node": ^20.17.6
    typedoc: ^0.25.13

  # Build & Development Tools - Fixed source-map version
  build:
    vite: ^5.4.10
    tsup: ^8.3.5
    "@vitejs/plugin-react": ^4.3.3
    source-map: ^0.7.6

  # Testing Stack - Stabilne 2.x verzije  
  testing:
    vitest: ^2.1.5
    "@testing-library/react": ^16.0.1
    "@testing-library/jest-dom": ^6.6.3
    "@testing-library/user-event": ^14.5.2
    jsdom: ^25.0.1
    vitest-axe: ^0.1.0
    "@axe-core/react": ^4.7.3

  # Storybook - Stabilna 8.x serija (bez problematičnih addon-a)
  storybook:
    storybook: ^8.3.5
    "@storybook/addon-a11y": ^8.3.5
    "@storybook/addon-essentials": ^8.3.5
    "@storybook/addon-interactions": ^8.3.5
    "@storybook/addon-docs": ^8.3.5
    "@storybook/react": ^8.3.5
    "@storybook/react-vite": ^8.3.5
    "@storybook/test": ^8.3.5
    "@storybook/test-runner": ^0.23.0
    chromatic: ^11.12.6

  # Code Quality Tools
  quality:
    eslint: ^9.15.0
    prettier: ^3.3.3
    "@typescript-eslint/parser": ^8.15.0
    "@typescript-eslint/eslint-plugin": ^8.15.0
    eslint-config-prettier: ^9.1.0
    eslint-plugin-react: ^7.36.1
    eslint-plugin-react-hooks: ^5.0.0

  # Monorepo & Build Tools (without Turbo)
  tooling:
    husky: ^9.1.6
    rimraf: ^6.0.1
    bundlesize: ^0.18.2
    "@changesets/cli": ^2.29.7
    "@changesets/changelog-github": ^0.5.1
    concurrently: ^8.2.2

  # Style & Design System Tools
  design:
    "style-dictionary": ^4.4.0

# Package manager specification
packageManager: "pnpm@9.12.3"