# Workspace packages configuration
packages:
  - "packages/*"
  - "apps/*"
  - "tools/*"
  - "."

# Catalogs - Centralizovano upravljanje verzijama kroz named catalogs
catalogs:
  # Core React Ecosystem - Stabilne verzije
  core:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1

  # TypeScript Ecosystem - Updated to latest stable
  typescript:
    typescript: ^5.6.3
    "@types/node": ^22.8.7
    typedoc: ^0.26.10

  # Build & Development Tools - Latest stable versions
  build:
    vite: ^5.4.10
    tsup: ^8.3.5
    "@vitejs/plugin-react": ^4.3.3
    "source-map": ^0.7.6

  # Testing Stack - Updated versions
  testing:
    vitest: ^2.1.5
    "@testing-library/react": ^16.0.1
    "@testing-library/jest-dom": ^6.6.3
    "@testing-library/user-event": ^14.5.2
    jsdom: ^25.0.1
    "vitest-axe": ^0.1.0
    "@axe-core/react": ^4.10.0
    "happy-dom": ^15.7.4
    jest-axe: ^8.0.0
  # Storybook - Latest 8.x series
  storybook:
    storybook: ^8.3.5
    "@storybook/addon-a11y": ^8.3.5
    "@storybook/addon-essentials": ^8.3.5
    "@storybook/addon-interactions": ^8.3.5
    "@storybook/addon-docs": ^8.3.5
    "@storybook/react": ^8.3.5
    "@storybook/react-vite": ^8.3.5
    "@storybook/test": ^8.3.5
    "@storybook/test-runner": ^0.23.0
    chromatic: ^11.12.6

  # Code Quality Tools - Latest versions with ESLint 9.x flat config support
  quality:
    eslint: ^9.15.0
    prettier: ^3.3.3
    "@typescript-eslint/parser": ^8.15.0
    "@typescript-eslint/eslint-plugin": ^8.15.0
    "eslint-config-prettier": ^9.1.0
    "eslint-plugin-react": ^7.36.1
    "eslint-plugin-react-hooks": ^5.0.0
    "eslint-plugin-react-refresh": ^0.4.14
    "@eslint/js": ^9.15.0
    "globals": ^15.12.0

  # Monorepo & Build Tools (without Turbo)
  tooling:
    husky: ^9.1.6
    rimraf: ^6.0.1
    bundlesize: ^0.18.2
    "@changesets/cli": ^2.29.7
    "@changesets/changelog-github": ^0.5.1
    concurrently: ^8.2.2  
    "del-cli": ^6.0.0         
    "gzip-size": ^7.0.0

  # Style & Design System Tools
  design:
    "style-dictionary": ^4.4.0

  docs:
    typedoc: ^0.26.10
    typedoc-plugin-markdown: ^4.2.9
    http-server: ^14.1.1

# Package manager specification
packageManager: "pnpm@9.12.3"